project:
  type: website
  output-dir: _site

website:
  title: "Powerlifting Performance Explorer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: exploration.qmd
        text: Exploration
      - href: story.qmd
        text: Story

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    embed-resources: true
