project:
  type: website
  output-dir: _site

website:
  title: "Muscle Gain Dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    embed-resources: true
